import ExcelJS from "exceljs";

export const exportTableToExcel = async (
  res,
  title,
  columns,
  rows,
  meta = {}
) => {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet(title);

  /* =========================
     HEADER ROW
  ========================= */
  sheet.addRow(columns);

  sheet.getRow(1).font = { bold: true };

  sheet.columns = columns.map(() => ({
    width: 20,
  }));

  /* =========================
     DATA ROWS
  ========================= */
  rows.forEach((row) => {
    sheet.addRow(row);
  });

  /* =========================
     META INFO
  ========================= */
  sheet.addRow([]);
  sheet.addRow([
    `Generated on: ${new Date().toLocaleString()}${
      meta.generatedBy ? ` | Generated by ${meta.generatedBy}` : ""
    }`,
  ]);

  res.setHeader(
    "Content-Type",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  );

  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${title.replace(/\s+/g, "_")}.xlsx`
  );

  await workbook.xlsx.write(res);
  res.end();
};
