import PDFDocument from "pdfkit";

export const exportTableToPDF = (res, title, columns, rows, meta = {}) => {
  const doc = new PDFDocument({
    margin: 40,
    size: "A4",
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${title.replace(/\s+/g, "_")}.pdf`
  );

  doc.pipe(res);

  /* =========================
     TITLE
  ========================= */
  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text(title, { align: "center" });

  doc.moveDown(1.5);

  /* =========================
     TABLE CONFIG
  ========================= */
  const pageWidth =
    doc.page.width - doc.page.margins.left - doc.page.margins.right;

  const columnWidth = pageWidth / columns.length;
  const getRowHeight = (doc, row, columnWidth) => {
  const heights = row.map(cell =>
    doc.heightOfString(String(cell ?? ""), {
      width: columnWidth - 10,
    })
  );

  return Math.max(...heights) + 12; // padding
};

  let y = doc.y;

  /* =========================
     HEADER ROW
  ========================= */
  doc.fontSize(10).font("Helvetica-Bold");

const headerHeight = getRowHeight(doc, columns, columnWidth);

columns.forEach((col, i) => {
  doc.rect(
    doc.page.margins.left + i * columnWidth,
    y,
    columnWidth,
    headerHeight
  ).stroke();

  doc.text(
    col,
    doc.page.margins.left + i * columnWidth + 5,
    y + 6,
    {
      width: columnWidth - 10,
      align: "center",
    }
  );
});

y += headerHeight;

  /* =========================
     DATA ROWS
  ========================= */
  doc.font("Helvetica").fontSize(9);

rows.forEach((row) => {
  const rowHeight = getRowHeight(doc, row, columnWidth);

  if (y + rowHeight > doc.page.height - doc.page.margins.bottom) {
    doc.addPage();
    y = doc.page.margins.top;
  }

  row.forEach((cell, i) => {
    doc.rect(
      doc.page.margins.left + i * columnWidth,
      y,
      columnWidth,
      rowHeight
    ).stroke();

    doc.text(
      String(cell ?? ""),
      doc.page.margins.left + i * columnWidth + 5,
      y + 6,
      {
        width: columnWidth - 10,
        align: "left",
      }
    );
  });

  y += rowHeight;
});
 

  /* =========================
     FOOTER
  ========================= */
  doc.moveDown(2);
  doc
    .fontSize(8)
    .fillColor("gray")
    .text(
      `Generated on ${new Date().toLocaleString()}${
        meta.generatedBy ? ` | Generated by ${meta.generatedBy}` : ""
      }`,
      { align: "center" }
    );

  doc.end();
};
