import PDFDocument from "pdfkit";
import Asset from "../models/assetModel.js";
import AssetHistory from "../models/assetHistoryModel.js";

export const exportAssetFullReportPDF = async (req, res) => {
  try {
    const asset = await Asset.findById(req.params.id).populate(
      "assignedTo",
      "name email",
    );

    if (!asset || asset.isDeleted) {
      return res.status(404).json({ message: "Asset not found" });
    }

    const history = await AssetHistory.find({ asset: asset._id })
      .populate("performedBy", "name email")
      .populate("assignedTo", "name email")
      .sort({ createdAt: 1 });

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${asset.name}-full-report.pdf`,
    );

    doc.pipe(res);

    /* =========================
       HEADER
    ========================= */
    doc
      .fontSize(20)
      .text("Company Name", { align: "center" })
      .fontSize(14)
      .text("ALLOC8 – Asset Management System", { align: "center" });

    doc.moveDown(1.5);
    doc.fontSize(16).text("Asset Full Report", { align: "center" });
    doc.moveDown(2);

    /* =========================
       ASSET SUMMARY
    ========================= */
    doc.fontSize(14).text("Asset Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Name          : ${asset.name}`);
    doc.text(`Category      : ${asset.category}`);
    doc.text(`Serial Number : ${asset.serialNumber || "N/A"}`);
    doc.text(`Status        : ${asset.status.toUpperCase()}`);
    doc.text(
      `Assigned To   : ${
        asset.assignedTo
          ? `${asset.assignedTo.name} (${asset.assignedTo.email})`
          : "Not Assigned"
      }`,
    );

    doc.moveDown(1.5);

    /* =========================
       MAINTENANCE HISTORY
    ========================= */
    doc.fontSize(14).text("Maintenance History", { underline: true });
    doc.moveDown(1);

    if (!asset.maintenance || asset.maintenance.length === 0) {
      doc.fontSize(11).text("No maintenance records found.");
    } else {
      asset.maintenance.forEach((m, index) => {
        doc.fontSize(12).text(`${index + 1}. ${m.reason || "Maintenance"}`);
        doc.fontSize(10);
        doc.text(
          `   Start Date       : ${m.startDate ? m.startDate.toISOString().split("T")[0] : "N/A"}`,
        );
        doc.text(
          `   End Date         : ${m.endDate ? m.endDate.toISOString().split("T")[0] : "N/A"}`,
        );
        doc.text(`   Notes            : ${m.notes || "N/A"}`);
        doc.text(`   Maintenance Cost : ₹${m.cost !== undefined ? m.cost : 0}`);
        
        doc.moveDown(0.5);
        doc.text(
          `Total Maintenance Cost : ₹${asset.totalMaintenanceCost || 0}`,
        );
        doc.text(`Maintenance Cost  : ${typeof m.cost === "number" ? `₹ ${m.cost}` : "Not Recorded"}`);

        doc.moveDown(0.8);
      });
    }

    doc.moveDown(1);

    /* =========================
       ASSET HISTORY
    ========================= */
    doc.fontSize(14).text("Asset History", { underline: true });
    doc.moveDown(1);

    if (history.length === 0) {
      doc.fontSize(11).text("No asset history found.");
    } else {
      history.forEach((h, index) => {
        doc
          .fontSize(12)
          .text(`${index + 1}. ${h.action.replace("_", " ").toUpperCase()}`);
        doc.fontSize(10);
        doc.text(`   Date        : ${h.createdAt.toISOString().split("T")[0]}`);
        doc.text(
          `   Performed By: ${
            h.performedBy
              ? `${h.performedBy.name} (${h.performedBy.email})`
              : "System"
          }`,
        );
        if (h.assignedTo) {
          doc.text(
            `   Assigned To : ${h.assignedTo.name} (${h.assignedTo.email})`,
          );
        }
        if (h.notes) {
          doc.text(`   Notes       : ${h.notes}`);
        }
        doc.moveDown(0.8);
      });
    }

    /* =========================
       FOOTER
    ========================= */
    doc.moveDown(2);
    doc
      .fontSize(9)
      .text(
        `Generated on: ${new Date().toLocaleString()} | Generated by: ${req.user.name} (${req.user.email})`,
        { align: "center" },
      );

    doc.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
