import PDFDocument from "pdfkit";
import Asset from "../models/assetModel.js";
import AssetHistory from "../models/assetHistoryModel.js";

export const exportAssetHistoryPDF = async (req, res) => {
  try {
    const asset = await Asset.findById(req.params.id);
    if (!asset || asset.isDeleted) {
      return res.status(404).json({ message: "Asset not found" });
    }

    const history = await AssetHistory.find({ asset: asset._id })
      .populate("performedBy", "name email")
      .populate("assignedTo", "name email")
      .sort({ createdAt: 1 });

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    // Headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${asset.name}-history.pdf`
    );

    doc.pipe(res);

    /* =========================
       HEADER
    ========================= */
    doc
      .fontSize(20)
      .text("Company Name", { align: "center" })
      .fontSize(14)
      .text("ALLOC8 – Asset Management System", { align: "center" });

    doc.moveDown(1.5);

    /* =========================
       ASSET SUMMARY
    ========================= */
    doc.fontSize(14).text("Asset Information", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Name          : ${asset.name}`);
    doc.text(`Category      : ${asset.category}`);
    doc.text(`Serial Number : ${asset.serialNumber || "N/A"}`);
    doc.text(`Current Status: ${asset.status.toUpperCase()}`);

    doc.moveDown(1.5);

    /* =========================
       HISTORY SECTION
    ========================= */
    doc.fontSize(14).text("History Timeline", { underline: true });
    doc.moveDown(1);

    if (history.length === 0) {
      doc.fontSize(11).text("No history records found.");
    }

    history.forEach((h, index) => {
      doc
        .fontSize(12)
        .text(
          `${index + 1}. ${h.action.replace("_", " ").toUpperCase()}`,
          { continued: false }
        );

      doc.fontSize(10);
      doc.text(`   Date        : ${h.createdAt.toISOString().split("T")[0]}`);
      doc.text(
        `   Performed By: ${
          h.performedBy
            ? `${h.performedBy.name} (${h.performedBy.email})`
            : "System"
        }`
      );

      if (h.assignedTo) {
        doc.text(
          `   Assigned To : ${h.assignedTo.name} (${h.assignedTo.email})`
        );
      }

      if (h.notes) {
        doc.text(`   Notes       : ${h.notes}`);
      }

      doc.moveDown(0.8);
    });

    /* =========================
       FOOTER
    ========================= */
    doc.moveDown(2);

    doc
      .fontSize(9)
      .text(
        `Generated on: ${new Date().toLocaleString()} | Generated by: ${req.user.name} (${req.user.email})`,
        { align: "center" }
      );

    doc.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
