import PDFDocument from "pdfkit";
import Asset from "../models/assetModel.js";

export const exportAllAssetsPDF = async (req, res) => {
  try {
    const assets = await Asset.find()
      .populate("assignedTo", "name email")
      .sort({ createdAt: 1 });

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=all-assets-report.pdf",
    );

    doc.pipe(res);

    /* =========================
       HEADER
    ========================= */
    doc
      .fontSize(20)
      .text("Company Name", { align: "center" })
      .fontSize(14)
      .text("ALLOC8 – Asset Management System", { align: "center" });

    doc.moveDown(1.5);
    doc.fontSize(16).text("All Assets Report", { align: "center" });
    doc.moveDown(2);

    /* =========================
       ASSET LIST
    ========================= */
    doc.fontSize(14).text("Asset List", { underline: true });
    doc.moveDown(1);

    if (assets.length === 0) {
      doc.fontSize(11).text("No assets found.");
    }

    let summary = {
      available: 0,
      assigned: 0,
      maintenance: 0,
      replaced: 0,
    };

    assets.forEach((asset, index) => {
      if (!asset.isDeleted && summary[asset.status] !== undefined) {
        summary[asset.status]++;
      }

      doc.fontSize(12).text(`${index + 1}. ${asset.name}`);
      doc.fontSize(10);
      doc.text(`   Category      : ${asset.category}`);
      doc.text(`   Serial Number : ${asset.serialNumber || "N/A"}`);
      doc.text(`   Status        : ${asset.status.toUpperCase()}`);
      doc.text(
        `   Assigned To   : ${
          asset.assignedTo
            ? `${asset.assignedTo.name} (${asset.assignedTo.email})`
            : "Not Assigned"
        }`,
      );
      doc.text(`   Record State  : ${asset.isDeleted ? "Inactive" : "Active"}`);
      doc.text(`   Asset Cost        : ₹ ${asset.assetCost || 0}`);
      doc.text(`   Maintenance Count : ${asset.maintenanceCount || 0}`);

      doc.text(`   Maintenance Cost  : ₹ ${asset.totalMaintenanceCost || 0}`);

      doc.moveDown(0.8);
    });

    /* =========================
       SUMMARY
    ========================= */
    doc.moveDown(1.5);
    doc.fontSize(14).text("Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Total Assets     : ${assets.length}`);
    doc.text(`Available        : ${summary.available}`);
    doc.text(`Assigned         : ${summary.assigned}`);
    doc.text(`Maintenance      : ${summary.maintenance}`);
    doc.text(`Replaced         : ${summary.replaced}`);
    doc.text(
      `Total Asset Value   : ₹ ${assets.reduce((s, a) => s + (a.assetCost || 0), 0)}`,
    );
    
    doc.text(
      `Total Maintenance   : ₹ ${assets.reduce((s, a) => s + (a.totalMaintenanceCost || 0), 0)}`,
    );

    /* =========================
       FOOTER
    ========================= */
    doc.moveDown(2);
    doc
      .fontSize(9)
      .text(
        `Generated on: ${new Date().toLocaleString()} | Generated by: ${req.user.name} (${req.user.email})`,
        { align: "center" },
      );

    doc.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
