import PDFDocument from "pdfkit";
import Asset from "../models/assetModel.js";

export const exportMaintenanceRecordsPDF = async (req, res) => {
  try {
    const assets = await Asset.find({ maintenance: { $exists: true, $ne: [] } })
      .select("name category maintenance")
      .sort({ createdAt: 1 });

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=maintenance-records-report.pdf",
    );

    doc.pipe(res);

    /* =========================
       HEADER
    ========================= */
    doc
      .fontSize(20)
      .text("Company Name", { align: "center" })
      .fontSize(14)
      .text("ALLOC8 – Asset Management System", { align: "center" });

    doc.moveDown(1.5);
    doc.fontSize(16).text("Maintenance Records Report", { align: "center" });
    doc.moveDown(2);

    /* =========================
       MAINTENANCE LIST
    ========================= */
    doc.fontSize(14).text("Maintenance Records", { underline: true });
    doc.moveDown(1);

    let total = 0;
    let activeCount = 0;
    let completedCount = 0;
    let index = 1;

    assets.forEach((asset) => {
      asset.maintenance.forEach((m) => {
        total++;

        if (m.isActive) activeCount++;
        else completedCount++;

        doc.fontSize(12).text(`${index}. ${asset.name}`);
        doc.fontSize(10);
        doc.text(`   Category          : ${asset.category}`);
        doc.text(`   Reason            : ${m.reason || "N/A"}`);
        doc.text(
          `   Start Date        : ${
            m.startDate ? m.startDate.toISOString().split("T")[0] : "N/A"
          }`,
        );
        doc.text(
          `   End Date          : ${
            m.endDate ? m.endDate.toISOString().split("T")[0] : "N/A"
          }`,
        );
        doc.text(
          `   Status            : ${m.isActive ? "Active" : "Completed"}`,
        );
        doc.text(`   Notes             : ${m.notes || "N/A"}`);
        doc.text(`   Maintenance Cost  : ${ typeof m.cost === "number" ? ` ${m.cost}` : "Not Recorded" }`);

        doc.moveDown(0.8);

        index++;
      });
    });

    if (total === 0) {
      doc.fontSize(11).text("No maintenance records found.");
    }

    /* =========================
       SUMMARY
    ========================= */
    doc.moveDown(1.5);
    doc.fontSize(14).text("Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Total Records     : ${total}`);
    doc.text(`Active Maintenance: ${activeCount}`);
    doc.text(`Completed         : ${completedCount}`);

    /* =========================
       FOOTER
    ========================= */
    doc.moveDown(2);
    doc
      .fontSize(9)
      .text(
        `Generated on: ${new Date().toLocaleString()} | Generated by: ${req.user.name} (${req.user.email})`,
        { align: "center" },
      );

    doc.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
