import PDFDocument from "pdfkit";
import Request from "../models/requestModel.js";

export const exportAllRequestsPDF = async (req, res) => {
  try {
    const requests = await Request.find()
      .populate("user", "name email")
      .populate("assignedAsset", "name category")
      .sort({ createdAt: 1 });

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=all-requests-report.pdf"
    );

    doc.pipe(res);

    /* =========================
       HEADER
    ========================= */
    doc
      .fontSize(20)
      .text("Company Name", { align: "center" })
      .fontSize(14)
      .text("ALLOC8 – Asset Management System", { align: "center" });

    doc.moveDown(1.5);
    doc.fontSize(16).text("All Requests Report", { align: "center" });
    doc.moveDown(2);

    /* =========================
       REQUEST LIST
    ========================= */
    doc.fontSize(14).text("Request List", { underline: true });
    doc.moveDown(1);

    let summary = {
      pending: 0,
      approved: 0,
      rejected: 0,
    };

    if (requests.length === 0) {
      doc.fontSize(11).text("No requests found.");
    }

    requests.forEach((reqItem, index) => {
      summary[reqItem.status]++;

      doc.fontSize(12).text(`${index + 1}. ${reqItem.user?.name || "Unknown User"}`);
      doc.fontSize(10);
      doc.text(`   Email          : ${reqItem.user?.email || "N/A"}`);
      doc.text(`   Asset Category : ${reqItem.assetCategory}`);
      doc.text(`   Reason         : ${reqItem.reason || "N/A"}`);
      doc.text(`   Status         : ${reqItem.status.toUpperCase()}`);
      doc.text(
        `   Assigned Asset : ${
          reqItem.assignedAsset
            ? `${reqItem.assignedAsset.name} (${reqItem.assignedAsset.category})`
            : "N/A"
        }`
      );
      doc.text(
        `   Requested On   : ${reqItem.createdAt.toISOString().split("T")[0]}`
      );
      doc.text(
        `   Processed On   : ${
          reqItem.status === "pending"
            ? "Not Processed"
            : reqItem.updatedAt.toISOString().split("T")[0]
        }`
      );
      doc.moveDown(0.8);
    });

    /* =========================
       SUMMARY
    ========================= */
    doc.moveDown(1.5);
    doc.fontSize(14).text("Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Total Requests : ${requests.length}`);
    doc.text(`Pending        : ${summary.pending}`);
    doc.text(`Approved       : ${summary.approved}`);
    doc.text(`Rejected       : ${summary.rejected}`);

    /* =========================
       FOOTER
    ========================= */
    doc.moveDown(2);
    doc
      .fontSize(9)
      .text(
        `Generated on: ${new Date().toLocaleString()} | Generated by: ${req.user.name} (${req.user.email})`,
        { align: "center" }
      );

    doc.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
