import PDFDocument from "pdfkit";
import User from "../models/userModel.js";
import Asset from "../models/assetModel.js";

export const exportAllEmployeesPDF = async (req, res) => {
  try {
    const users = await User.find().select("-password").sort({ name: 1 });

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=all-employees-report.pdf"
    );

    doc.pipe(res);

    /* =========================
       HEADER
    ========================= */
    doc
      .fontSize(20)
      .text("Company Name", { align: "center" })
      .fontSize(14)
      .text("ALLOC8 – Asset Management System", { align: "center" });

    doc.moveDown(1.5);
    doc.fontSize(16).text("All Employees Report", { align: "center" });
    doc.moveDown(2);

    /* =========================
       EMPLOYEE LIST
    ========================= */
    doc.fontSize(14).text("Employee List", { underline: true });
    doc.moveDown(1);

    let activeCount = 0;
    let inactiveCount = 0;

    for (let i = 0; i < users.length; i++) {
      const user = users[i];

      if (user.isDeleted) inactiveCount++;
      else activeCount++;

      const assetCount = await Asset.countDocuments({
        assignedTo: user._id,
        isDeleted: false,
      });

      doc.fontSize(12).text(`${i + 1}. ${user.name}`);
      doc.fontSize(10);
      doc.text(`   Email        : ${user.email}`);
      doc.text(`   Department   : ${user.department || "N/A"}`);
      doc.text(`   Role         : ${user.role}`);
      doc.text(`   Status       : ${user.isDeleted ? "Inactive" : "Active"}`);
      doc.text(`   Assets Count : ${assetCount}`);
      doc.moveDown(0.8);
    }

    /* =========================
       SUMMARY
    ========================= */
    doc.moveDown(1.5);
    doc.fontSize(14).text("Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Total Employees : ${users.length}`);
    doc.text(`Active          : ${activeCount}`);
    doc.text(`Inactive        : ${inactiveCount}`);

    /* =========================
       FOOTER
    ========================= */
    doc.moveDown(2);
    doc
      .fontSize(9)
      .text(
        `Generated on: ${new Date().toLocaleString()} | Generated by: ${req.user.name} (${req.user.email})`,
        { align: "center" }
      );

    doc.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
