//UNWANTED FILE IF DELETED BUG OCCURS

import PDFDocument from "pdfkit";
import User from "../models/userModel.js";
import Asset from "../models/assetModel.js";

export const exportUserAssetsPDF = async (req, res) => {
  try {
    const user = await User.findById(req.params.id).select("-password");

    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    const assets = await Asset.find({
      assignedTo: user._id,
      isDeleted: false,
    });

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${user.name}-asset-allocation.pdf`
    );

    doc.pipe(res);

    /* =========================
       HEADER
    ========================= */
    doc
      .fontSize(20)
      .text("Company Name", { align: "center" })
      .fontSize(14)
      .text("ALLOC8 – Asset Management System", { align: "center" });

    doc.moveDown(1.5);

    doc
      .fontSize(16)
      .text("User Asset Allocation Report", { align: "center" });

    doc.moveDown(2);

    /* =========================
       USER INFO
    ========================= */
    doc.fontSize(14).text("User Information", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11);
    doc.text(`Name       : ${user.name}`);
    doc.text(`Email      : ${user.email}`);
    doc.text(`Department : ${user.department || "N/A"}`);
    doc.text(`Status     : ${user.isDeleted ? "Inactive" : "Active"}`);

    doc.moveDown(1.5);

    /* =========================
       ASSET LIST
    ========================= */
    doc.fontSize(14).text("Assigned Assets", { underline: true });
    doc.moveDown(1);

    if (assets.length === 0) {
      doc.fontSize(11).text("No assets assigned to this user.");
    }

    assets.forEach((asset, index) => {
      doc.fontSize(12).text(`${index + 1}. ${asset.name}`);
      doc.fontSize(10);
      doc.text(`   Category      : ${asset.category}`);
      doc.text(`   Serial Number : ${asset.serialNumber || "N/A"}`);
      doc.text(`   Status        : ${asset.status.toUpperCase()}`);
      doc.moveDown(0.8);
    });

    /* =========================
       FOOTER
    ========================= */
    doc.moveDown(2);
    doc
      .fontSize(9)
      .text(
        `Generated on: ${new Date().toLocaleString()} | Generated by: ${req.user.name} (${req.user.email})`,
        { align: "center" }
      );

    doc.end();
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
